"""Darlene — the Bottomless Cup, behind the counter. Hand-pixeled,
single view (3/4 toward the door), idle + 2 talk frames.

Visual reference (her LOOK line): apron, pencil behind the ear, coffee
pot in permanent orbit. Waist-up sprite — the painted counter provides
the rest of her (the classic Sierra bartender trick): the art ends
clean at the apron waist and the bottom edge sits on the counter line.

Frame 30x38, anchor (14, 37) = the point that lands on the counter top.
Talk frames: the pot orbits (rises), the free hand gestures. No ground
shadow — she has no visible feet to cast one.
"""

from spritelib import compose, parse_grid

KEY = {
    "o": "outline",
    "Y": "hair_sandy_m", "y": "hair_sandy_d", "i": "hair_sandy_l",
    "T": "skin_tan_m", "u": "skin_tan_d", "e": "skin_tan_l",
    "D": "teal_m", "d": "teal_d", "l": "teal_l",
    "A": "apron_l", "a": "apron_m", "q": "apron_d",
    "F": "coffee", "g": "glass_hi",
    "p": "pencil",
}

# Head + bun + torso + apron + right arm; the pot arm overlays at left.
BODY = """
..................oooo........
............oooo.oYYyYo.......
...........oYYYYoYiYYyo.......
..........oYiYYYYYYYyyYo......
..........oYiYYYYYYYYyo.......
..........oYYYYYYYYYyYo.......
..........oYTTTTTTYYyYo.......
..........oTTTTTTTTYYYooo.....
..........oTToTTToTYYopppo....
..........oTTTTTTTTYYooooo....
..........oTTTTTTTTYo.........
..........oTuTTTTuTo..........
..........oTTooooTTo..........
...........oTTTTTTo...........
...........ouTTTTuo...........
............oTTTTo............
..........ooddDDddoo..........
........ooDDdDDDDdDDoo........
.......oDDDDoADDAoDDDDo.......
......oDDDDoAAAAAAoDDDDo......
......oDDDoAAAAAAAAoDDDo......
.....oDDDDoAAAAAAAAoDDDDo.....
.....oDDDoAAAAAAAAAAoDDDo.....
.....oDDDoAAAAAAAAAAoDDDo.....
.....odDDoAAAAAAAAAAoDDdo.....
.....odDooAAAAAAAAAAooDdo.....
.....oDDoAAAAAAAAAAAAoDDo.....
.....oDDoAAAAAAAAAAAAoDDo.....
.....odDoAAAAAAAAAAAAoDdo.....
.....odooAAAAAAAAAAAAoodo.....
.....oToAAAAAAAAAAAAAAoTo.....
.....oToAAAAAAAAAAAAAAoTo.....
....oTToAAAAAAAAAAAAAAoTTo....
....oTToAAAAAAAAAAAAAAoTTo....
....ouuoAAaAAAAAAAAaAAouuo....
....oooqaAaAAAAAAAAaAaqooo....
.....oqaaAaAAAAAAAAaAaaqo.....
.....oqqqqaaaaaaaaaaqqqqo.....
"""

# Coffee pot + arm (overlays the left side). Placed lower = idle,
# raised = talk. Glass carafe, coffee two-thirds full, handle gripped.
ARM_POT = """
......oDDo..
....ooDDDo..
...oTTTDdo..
...oTTTo....
....oTTo....
....oTTo....
..oooooToo..
.ogggggoTo..
.ogFFFFooo..
.oFFFFFFo...
..oFFFFo....
...oooo.....
"""

# Free-hand gesture for the second talk frame (screen-right side).
HAND_UP = """
...oTTo
..oTTTo
.oTTTo.
oDTTo..
oDDo...
odo....
"""

FRAME_W, FRAME_H = 30, 38

_body = parse_grid(BODY, KEY)
_pot = parse_grid(ARM_POT, KEY)
_hand = parse_grid(HAND_UP, KEY)


def _frame(pot_dy, hand_up):
    parts = [(_body, 0, 0), (_pot, 0, 15 + pot_dy)]
    if hand_up:
        parts.append((_hand, 23, 12))
    return compose(FRAME_W, FRAME_H, parts)


def build():
    return {
        "darlene": [[
            _frame(0, False),
            _frame(-2, False),
            _frame(-1, True),
        ]]
    }
