"""Darlene — the Bottomless Cup, behind the counter. Hand-pixeled,
single view (3/4 toward the door), idle + 2 talk frames.

Visual reference (her LOOK line): apron, pencil behind the ear, coffee
pot in permanent orbit. Waist-up sprite — the painted counter provides
the rest of her (the classic Sierra bartender trick): the art ends
clean at the apron waist and the bottom edge tucks behind the counter
top's far edge.

Arms are PARTS, never baked into the body: every frame composes exactly
two — the pot arm (left) and one right arm (down or waving). Talk frames
swap the right arm and orbit the pot; nothing stacks.

Frame 30x38, anchor (14, 37) = the row that tucks behind the counter.
No ground shadow — she has no visible feet to cast one.
"""

from spritelib import compose, parse_grid

KEY = {
    "o": "outline",
    "Y": "hair_sandy_m", "y": "hair_sandy_d", "i": "hair_sandy_l",
    "T": "skin_tan_m", "u": "skin_tan_d", "e": "skin_tan_l",
    "D": "teal_m", "d": "teal_d", "l": "teal_l",
    "A": "apron_l", "a": "apron_m", "q": "apron_d",
    "F": "coffee", "g": "glass_hi",
    "p": "pencil",
}

# Head + bun + armless torso: dress shoulders, apron bib and skirt,
# clean side edges for the arm parts to overlay.
BODY = """
..................oooo........
............oooo.oYYyYo.......
...........oYYYYoYiYYyo.......
..........oYiYYYYYYYyyYo......
..........oYiYYYYYYYYyo.......
..........oYYYYYYYYYyYo.......
..........oYTTTTTTYYyYo.......
..........oTTTTTTTTYYYooo.....
..........oTToTTToTYYopppo....
..........oTTTTTTTTYYooooo....
..........oTTTTTTTTYo.........
..........oTuTTTTuTo..........
..........oTTooooTTo..........
...........oTTTTTTo...........
...........ouTTTTuo...........
............oTTTTo............
..........ooddDDddoo..........
........ooDDdDDDDdDDoo........
.......oDDDDoADDAoDDDDo.......
.......oDDDoAAAAAAoDDDo.......
.......oDDoAAAAAAAAoDDo.......
.......oDDoAAAAAAAAoDDo.......
.......oDDoAAAAAAAAoDDo.......
.......oDDoAAAAAAAAoDDo.......
.......odDoAAAAAAAAoDdo.......
.......odooAAAAAAAAoodo.......
......oDDoAAAAAAAAAAoDDo......
......oDDoAAAAAAAAAAoDDo......
......odDoAAAAAAAAAAoDdo......
......odDoAAAAAAAAAAoDdo......
......oDDoAAAAAAAAAAoDDo......
......oDDoAAAAAAAAAAoDDo......
......oDdoAAAAAAAAAAoDdo......
......oDdoAAAAAAAAAAodDo......
......oDdoAAaAAAAaAAodDo......
......oooqaAaAAAAaAaqooo......
......oqaaAaAAAAAAaAaaqo......
......oqqqqaaaaaaaaqqqqo......
"""

# The pot arm (left, screen-left): shoulder to hand to carafe, one
# connected piece. Placed lower = idle, raised = talk (the orbit).
ARM_POT = """
.......oDDo.
.....ooDDDo.
....oTTTDdo.
...oTTTTo...
...oTTo.....
..ooooooo...
..ogggggo...
..ogFFFFo...
..oFFFFFo...
...oFFFo....
....ooo.....
"""

# Right arm, hanging at her side (idle + first talk frame).
ARM_DOWN = """
.oDDo.
oDDDo.
oDDo..
oDdo..
oDdo..
oTTo..
oTo...
.o....
"""

# Right arm, raised in a wave (second talk frame — replaces ARM_DOWN).
ARM_WAVE = """
.....oTTo
....oTTTo
...oTTo..
.oDDTo...
oDDDo....
oDDo.....
.oo......
"""

FRAME_W, FRAME_H = 30, 38

_body = parse_grid(BODY, KEY)
_pot = parse_grid(ARM_POT, KEY)
_down = parse_grid(ARM_DOWN, KEY)
_wave = parse_grid(ARM_WAVE, KEY)

POT_X, POT_Y = 1, 16
RIGHT_X, RIGHT_Y = 19, 17


def _frame(pot_dy, wave):
    parts = [(_body, 0, 0), (_pot, POT_X, POT_Y + pot_dy)]
    if wave:
        parts.append((_wave, RIGHT_X, RIGHT_Y - 4))
    else:
        parts.append((_down, RIGHT_X, RIGHT_Y))
    return compose(FRAME_W, FRAME_H, parts)


def build():
    return {
        "darlene": [[
            _frame(0, False),
            _frame(-2, False),
            _frame(-1, True),
        ]]
    }
