"""Dot — Kim's Nails, the chair under the bonnet dryer. Hand-pixeled,
single view (3/4 toward the room), idle + 2 talk frames.

Visual reference (her LOOK line): Beautification Committee chair,
membership one, nails mid-cure, gestures with her elbows to protect the
polish — every pronouncement a small flightless bird taking off. Drawn
SEATED with no chair of her own (the Merle trick): she sits on the
painted salon chair, anchor at her shoe soles.

Signature pop: the lavender cardigan (no one else owns purple). Silver
hair in rose curlers, cat-eye glasses, fresh rose fingertips on hands
held flat and splayed — the hands NEVER close. Talk frames wing the
elbows; the nails stay level throughout, as physics and Kim demand.

Arms are PARTS, never baked into the body: every frame composes exactly
two — left and right — in rest or winged pose. Frame 34x48, anchor
(16, 47) = shoe soles on the painted chair's footrest line.
"""

from spritelib import compose, parse_grid

KEY = {
    "o": "outline",
    "H": "hair_gray_l", "h": "hair_gray_m",
    "C": "rose_m", "c": "rose_l",
    "T": "skin_pale_m", "u": "skin_pale_d", "e": "skin_pale_l",
    "g": "glass_hi",
    "L": "lavender_m", "l": "lavender_d", "s": "lavender_l",
    "W": "white",
    "E": "shoe_black_m",
    "n": "hair_gray_d",
}

# Curler-crowned head + cardigan torso + skirted lap + shins; seated
# facing left. Arm parts overlay at the shoulders.
BODY = """
..........ooooooo.................
........ooCHHCHHCoo...............
.......oCHHCCHCCHHCo..............
......oHCCHHCHHCHCCHo.............
......oCHHCCHCCHHCHHo.............
......oHCCHHCHHCCHCHo.............
......ohHHhHHhHHhHHho.............
......ohoggoTTToggoho.............
......oooggoTTToggooo.............
......oToooTTTTTooTo..............
......oToTTTTTTTTToo..............
......oTuTTTTTTTTTo...............
......oTTooTTTTouTo...............
.......oTTTTTTTTTo................
.......ouTTTTTTuo.................
........ooTTTToo..................
.......oosWWWsoo..................
......osLsWWWsLso.................
.....osLLoWWWoLLso................
.....oLLLoWWWoLLLo................
.....oLLLooWooLLLo................
.....oLLLLoooLLLLo................
.....oLLLLLLLLLLLo................
.....oLLLLLLLLLLLo................
.....olLLLLLLLLLlo................
.....olLLLLLLLLLlo................
.....oLLLLLLLLLLLo................
.....oLLLLLLLLLLLo................
.....olLLLLLLLLllo................
......ooLLLLLLLoo.................
......ollllllllllo................
.....ollllllllllllo...............
....olllllllllllllo...............
....ollllllllllllo................
....ollllllllllllo................
....olllllllllllo.................
....ooollllllooo..................
......ohhooohho...................
......ohhohohho...................
......ohhohohho...................
......ohhohohho...................
......ohhohohho...................
......ohhohohho...................
......ohhohohho...................
......ohhohohho...................
......oEEooEEo....................
.....oEEEooEEEo...................
....oEEEEoEEEEo...................
.....ooooooooo....................
"""

# Left arm (screen-left), resting: forearm level, hand flat, fingers
# splayed, fresh rose tips. The nails ride level in every pose.
ARM_L_REST = """
.oLLo......
oLLLo......
oLLo.......
oLLo.......
oTTTTo.....
oeTeTeo....
.oCoCoCo...
..ooooo....
"""

# Left arm winged: elbow out and up, hand still flat (the takeoff).
ARM_L_WING = """
......oLLo.
...ooLLLo..
.ooLLLo....
oLLLo......
oTTTTo.....
oeTeTeo....
.oCoCoCo...
..ooooo....
"""

# Right arm (screen-right), resting.
ARM_R_REST = """
......oLLo.
......oLLLo
.......oLLo
.......oLLo
.....oTTTTo
....oeTeTeo
...oCoCoCo.
....ooooo..
"""

# Right arm winged.
ARM_R_WING = """
.oLLo......
..oLLLoo...
....oLLLoo.
......oLLLo
.....oTTTTo
....oeTeTeo
...oCoCoCo.
....ooooo..
"""

FRAME_W, FRAME_H = 34, 48

_body = parse_grid(BODY, KEY)
_l_rest = parse_grid(ARM_L_REST, KEY)
_l_wing = parse_grid(ARM_L_WING, KEY)
_r_rest = parse_grid(ARM_R_REST, KEY)
_r_wing = parse_grid(ARM_R_WING, KEY)

L_X, L_Y = 0, 17
R_X, R_Y = 12, 17


def _frame(wing, lift=0):
    left = _l_wing if wing else _l_rest
    right = _r_wing if wing else _r_rest
    return compose(FRAME_W, FRAME_H, [
        (_body, 0, 0),
        (left, L_X, L_Y - lift),
        (right, R_X, R_Y - lift),
    ])


def build():
    return {
        "dot": [[
            _frame(False),
            _frame(True, 1),
            _frame(True, 2),
        ]]
    }
