"""Gary — Main Street neighbor. Hand-pixeled, single view (front 3/4),
idle + 2 talk frames. The hose runs in every frame; canon says so.

Visual reference (his LOOK line): watering a dead lawn with a hose that
works fine. Powder-blue polo, khaki cargo shorts, tube socks, dad
sneakers, sunburn, not much hair. Talk frames bellow: free arm rises,
head tips back, mouth opens — the hose never wavers.

Frame 40x52, feet ground row y=50, anchor (19, 51).
"""

from spritelib import compose, parse_grid

KEY = {
    "o": "outline", "w": "shadow",
    "r": "skin_ruddy_m", "R": "skin_ruddy_d", "e": "skin_ruddy_l",
    "H": "hair_gray_m", "h": "hair_gray_d",
    "P": "polo_m", "p": "polo_d", "L": "polo_l",
    "K": "khaki_m", "k": "khaki_d", "Q": "khaki_l",
    "W": "white",
    "N": "sneaker_m", "n": "sneaker_d", "M": "sneaker_l",
    "G": "hose_m", "g": "hose_d",
    "B": "brass", "A": "water",
}

# Neck to feet: polo torso, left arm + running hose + water baked in,
# right-arm slot empty (the talk arms overlay at the right shoulder).
# Placed at frame y=15; ground row is the last row.
BASE = """
.................orro...................
............ooooorrooooo................
...........oPPPPLLLLPPPPPo..............
..........oPPPPPPPPPPPPPPPo.............
.........oPPPPPPPPPPPPPPPPPo............
........oPPpoPPPPPPPPPPPoPPPo...........
........oPpo.oPPPPPPPPPo.oPPo...........
.......oPpo..oPPPPPPPPPo.oPPo...........
.......oPpo..oPPPPPPPPPo..oPo...........
......oppo...oPPPPPPPPPo..oPo...........
......orro...oPPPPPPPPPPo.oPo...........
......orro...oPPPPPPPPPPooPo............
......oreo..oPPPPPPPPPPPPoo.............
......orro..oPPPPPPPPPPPPo..............
.......oo...oPPPPPPPPPPPPo..............
......oBBo..opppPPPPPPpppo..............
......oBo..oKKKKKKKKKKKKKKo.............
.....oGGo..oKKKKKKkkKKKKKKKo............
.....oGgo..oKQKKKKkkKKKKQKKo............
....AoGgo..oKQkKKKkkKKKKQkKo............
....AoGgo..oKQkKKKkkKKKKQkKo............
...A.oGgo..oKQkKKko.oKKKQkKo............
...A.oGgo..oKkKKKko.oKKKkkKo............
...A.oGgo...okKKKo...oKKko..............
..A..oGgo...oKKKKo...oKKKo..............
..A..oGgo...orrrro...orrro..............
..A...oGgo..orrro.....orro..............
..A...oGgo..oRrro.....oRro..............
.A....oGgo..orrro.....orro..............
.A.....oGgo.orrro.....orro..............
.A.....oGgooorro......orro..............
.AA.....oGgorrro......orro..............
..AA.....oGgWWWo......oWWWo.............
..oAo.....oWWWWo......oWWWo.............
..oAAo....oWWWo.......oWWo..............
...AAA...oNNNNo......oNNNo..............
..AAAAA.oMNNNNNo....oMNNNNNo............
.oAAAAAooMNNNNNNo...oMNNNNNNo...........
..ooooo.onnNNNNNo...onnNNNNNo...........
.........ooooooo.....ooooooo............
"""

HEAD = """
.....ooooo....
....orrrrro...
...orrrrrrro..
..oHrrrrrrHo..
..oHrrrrrrHo..
..ohrorrorho..
..ohrrrrrrho..
..oHrRrrRrHo..
...orrrrrro...
...orrooror...
....orrrro....
.....oooo.....
"""

HEAD_TALK = """
.....ooooo....
....orrrrro...
...orrrrrrro..
..oHrrrrrrHo..
..oHrrrrrrHo..
..ohrorrorho..
..ohrrrrrrho..
..oHrRrrRrHo..
...orroooro...
...orroooro...
....orrrro....
.....oooo.....
"""

# Free arm (screen-right): down / half raised / high with open palm.
ARM_DOWN = """
oPPo....
oPPo....
opPo....
oppo....
orro....
orro....
oRro....
orro....
orro....
.oro....
..o.....
"""

ARM_HALF = """
....oPo.
..oPPPo.
.oPPpo..
oPppo...
orro....
orro....
oro.....
.o......
........
........
"""

ARM_HIGH = """
......oro
....ororo
...orrro.
..oPrro..
..oPPo...
.oPPo....
.oPpo....
.opo.....
.oo......
.........
"""

SHADOW = """
.....wwwwwwwwwwwwwwwww......
...wwwwwwwwwwwwwwwwwwwww....
.....wwwwwwwwwwwwwwwww......
"""

FRAME_W, FRAME_H = 40, 52

_base = parse_grid(BASE, KEY)
_head = parse_grid(HEAD, KEY)
_head_talk = parse_grid(HEAD_TALK, KEY)
_arms = {n: parse_grid(g, KEY) for n, g in
         {"down": ARM_DOWN, "half": ARM_HALF, "high": ARM_HIGH}.items()}
_shadow = parse_grid(SHADOW, {"w": "shadow"})

BASE_Y = 11           # neck row of BASE lands at frame y=12
HEAD_X, HEAD_Y = 12, 2
ARM_X, ARM_Y = 25, 18


def _frame(head, head_dy, arm):
    return compose(FRAME_W, FRAME_H, [
        (_shadow, 6, 48),
        (_base, 0, BASE_Y),
        (head, HEAD_X, HEAD_Y + head_dy),
        (_arms[arm], ARM_X, ARM_Y),
    ])


def build():
    return {
        "gary": [[
            _frame(_head, 0, "down"),
            _frame(_head_talk, 0, "half"),
            _frame(_head_talk, -1, "high"),
        ]]
    }
