"""Kim — Kim's Nails, standing at her nail station. Hand-pixeled,
single view (3/4 toward the room), idle + 2 talk frames.

Visual reference (her LOOK line): mid-manicure, runs the room without
looking up, the mirror does her watching. STANDING sprite — the real
salon art gave her a small marble station with the client's chair in
front of it, so the behind-furniture waist-up trick has nothing to hide
behind; Kim works on her feet, the way she does everything.

Signature pop: the rose tunic (nobody else in the cast owns pink), now
hip-length over black slacks and white salon flats. Sleek black bob,
gold claw clip, white trim collar. Props carry the silhouette: the
emery board never leaves her left hand.

Arms are PARTS, never baked into the body: every frame composes exactly
two — the file arm (left) and one right arm (resting or pointing). Talk
frames lift the file mid-flourish, then the right hand points you where
you're going; nothing stacks.

Frame 30x50, anchor (14, 47) = feet between the heels. Ground shadow
baked (standers cast one; it must never slide).
"""

from spritelib import compose, parse_grid

KEY = {
    "o": "outline",
    "K": "hair_brown_d", "k": "hair_brown_m",
    "b": "brass",
    "T": "skin_pale_m", "u": "skin_pale_d", "e": "skin_pale_l",
    "R": "rose_m", "r": "rose_d", "s": "rose_l",
    "W": "white",
    "F": "file_board",
    "B": "shoe_black_m", "n": "shoe_black_d",
    "S": "sneaker_l",
    "x": "shadow",
}

# Head + bob + armless hip-length tunic + slacks + flats: clean side
# edges through the sleeve rows for the arm parts to overlay.
BODY = """
..........ooooooo.............
........ooKKKKKKKoo...........
.......oKKKKKKKKKKKo..........
......oKKkKKKKKKKKKKo.........
......oKkKKKKKKKKKKKo.........
......oKkKKKKKKKKKKKobo.......
......oKKoTTTTTTToKKobo.......
......oKKoTeTTTeTToKKo........
......oKKoToTTToTToKKo........
......oKKoTTTTTTTToKKo........
......oKKoTTTTTTTToKKo........
......oKKKoTuTTuToKKKo........
......oKKKooTTTTooKKKo........
.......oKKo.oooo.oKKo.........
.......ooo..oTTo..ooo.........
............oTTo..............
...........ooTTeo.............
.........oosWWWWsoo...........
........osRsWooWsRso..........
.......osRRsoWWosRRso.........
.......oRRRRoWWoRRRRo.........
.......oRRRooooooRRRo.........
.......oRRoRRRRRRoRRo.........
.......oRRoRRRRRRoRRo.........
.......orRoRRRRRRoRro.........
.......orooRRRRRRooro.........
......oRRoRRRRRRRRoRRo........
......oRRoRRRRRRRRoRRo........
......orRoRRRRRRRRoRro........
.......ooRRRRsRRRRRoo.........
........oRRRsRsRRRRo..........
........oRRRRsRRRRRo..........
........oRRRRRRRRRRo..........
........orRRRRRRRRro..........
........orrrrrrrrrro..........
........oBBBBooBBBBo..........
........oBBBBooBBBBo..........
........oBBBBooBBBBo..........
........oBBBBooBBBBo..........
........oBBnBooBnBBo..........
........oBBBBooBBBBo..........
........oBBBBooBBBBo..........
........onBBBooBBBno..........
........oSSSSooSSSSo..........
.......oSSSSSooSSSSSo.........
........ooooo..ooooo..........
"""

# Baked ground shadow — drawn under the body so it never slides.
SHADOW = """
..xxxxxxxxxxxxxx..
xxxxxxxxxxxxxxxxxx
..xxxxxxxxxxxxxx..
"""

# The file arm (left, screen-left): shoulder to hand, emery board held
# working-level. Placed lower = idle, raised = the talk flourish.
ARM_FILE = """
.....oRRo...
....oRRRo...
...oRRRo....
...oRRo.....
..oTTo......
..oTTo......
oFFTTo......
oFFFoo......
.oooo.......
"""

# Right arm resting at the table edge (idle + first talk frame).
ARM_REST = """
.oRRo.
oRRRo.
oRRo..
oRro..
oTTo..
oTTo..
.oo...
"""

# Right arm raised, one finger out — Kim pointing you at your next task
# without looking up (second talk frame — replaces ARM_REST).
ARM_POINT = """
......oTo
.....oTTo
....oTTo.
.oRRTo...
oRRRo....
oRRo.....
.oo......
"""

FRAME_W, FRAME_H = 30, 50

_body = parse_grid(BODY, KEY)
_shadow = parse_grid(SHADOW, KEY)
_file = parse_grid(ARM_FILE, KEY)
_rest = parse_grid(ARM_REST, KEY)
_point = parse_grid(ARM_POINT, KEY)

FILE_X, FILE_Y = 1, 18
RIGHT_X, RIGHT_Y = 20, 19


def _frame(file_dy, point):
    parts = [(_shadow, 6, 45), (_body, 0, 0), (_file, FILE_X, FILE_Y + file_dy)]
    if point:
        parts.append((_point, RIGHT_X, RIGHT_Y - 4))
    else:
        parts.append((_rest, RIGHT_X, RIGHT_Y))
    return compose(FRAME_W, FRAME_H, parts)


def build():
    return {
        "kim": [[
            _frame(0, False),
            _frame(-2, False),
            _frame(-1, True),
        ]]
    }
