"""Kim — Kim's Nails, behind the manicure table. Hand-pixeled, single
view (3/4 toward the room), idle + 2 talk frames.

Visual reference (her LOOK line): mid-manicure, runs the room without
looking up, the mirror does her watching. Waist-up sprite — the painted
manicure table provides the rest of her (the Darlene counter trick):
the art ends clean at the tunic waist and the bottom row tucks behind
the table's FAR edge.

Signature pop: the rose tunic (nobody else in the cast owns pink).
Sleek black bob, gold claw clip, white trim collar. Props carry the
silhouette: the emery board never leaves her left hand.

Arms are PARTS, never baked into the body: every frame composes exactly
two — the file arm (left) and one right arm (resting or pointing). Talk
frames lift the file mid-flourish, then the right hand points you where
you're going; nothing stacks.

Frame 30x40, anchor (14, 39) = the row that tucks behind the table.
No ground shadow — she has no visible feet to cast one.
"""

from spritelib import compose, parse_grid

KEY = {
    "o": "outline",
    "K": "hair_brown_d", "k": "hair_brown_m",
    "b": "brass",
    "T": "skin_pale_m", "u": "skin_pale_d", "e": "skin_pale_l",
    "R": "rose_m", "r": "rose_d", "s": "rose_l",
    "W": "white",
    "F": "file_board",
}

# Head + bob + armless tunic torso: clean side edges for the arm parts.
BODY = """
..........ooooooo.............
........ooKKKKKKKoo...........
.......oKKKKKKKKKKKo..........
......oKKkKKKKKKKKKKo.........
......oKkKKKKKKKKKKKo.........
......oKkKKKKKKKKKKKobo.......
......oKKoTTTTTTToKKobo.......
......oKKoTeTTTeTToKKo........
......oKKoToTTToTToKKo........
......oKKoTTTTTTTToKKo........
......oKKoTTTTTTTToKKo........
......oKKKoTuTTuToKKKo........
......oKKKooTTTTooKKKo........
.......oKKo.oooo.oKKo.........
.......ooo..oTTo..ooo.........
............oTTo..............
...........ooTTeo.............
.........oosWWWWsoo...........
........osRsWooWsRso..........
.......osRRsoWWosRRso.........
.......oRRRRoWWoRRRRo.........
.......oRRRooooooRRRo.........
.......oRRoRRRRRRoRRo.........
.......oRRoRRRRRRoRRo.........
.......orRoRRRRRRoRro.........
.......orooRRRRRRooro.........
......oRRoRRRRRRRRoRRo........
......oRRoRRRRRRRRoRRo........
......orRoRRRRRRRRoRro........
......orRoRRRRsRRRoRro........
......oRRoRRRsRsRRoRRo........
......oRRoRRRRsRRRoRRo........
......oRroRRRRRRRRorRo........
......oRroRRRRRRRRorRo........
......oRroRRRRRRRRorRo........
......ooooRRRRRRRRoooo........
.......orrRRRRRRRRrro.........
.......orrrRRRRRRrrro.........
.......orrrrrrrrrrrro.........
.......oooooooooooooo.........
"""

# The file arm (left, screen-left): shoulder to hand, emery board held
# working-level. Placed lower = idle, raised = the talk flourish.
ARM_FILE = """
.....oRRo...
....oRRRo...
...oRRRo....
...oRRo.....
..oTTo......
..oTTo......
oFFTTo......
oFFFoo......
.oooo.......
"""

# Right arm resting at the table edge (idle + first talk frame).
ARM_REST = """
.oRRo.
oRRRo.
oRRo..
oRro..
oTTo..
oTTo..
.oo...
"""

# Right arm raised, one finger out — Kim pointing you at your next task
# without looking up (second talk frame — replaces ARM_REST).
ARM_POINT = """
......oTo
.....oTTo
....oTTo.
.oRRTo...
oRRRo....
oRRo.....
.oo......
"""

FRAME_W, FRAME_H = 30, 40

_body = parse_grid(BODY, KEY)
_file = parse_grid(ARM_FILE, KEY)
_rest = parse_grid(ARM_REST, KEY)
_point = parse_grid(ARM_POINT, KEY)

FILE_X, FILE_Y = 1, 18
RIGHT_X, RIGHT_Y = 20, 19


def _frame(file_dy, point):
    parts = [(_body, 0, 0), (_file, FILE_X, FILE_Y + file_dy)]
    if point:
        parts.append((_point, RIGHT_X, RIGHT_Y - 4))
    else:
        parts.append((_rest, RIGHT_X, RIGHT_Y))
    return compose(FRAME_W, FRAME_H, parts)


def build():
    return {
        "kim": [[
            _frame(0, False),
            _frame(-2, False),
            _frame(-1, True),
        ]]
    }
