"""Mel Function — the player. Hand-pixeled part grids, compiled into four
outfit sheets (data/schema.md "Sprites"): mel_base (hoodie + joggers),
mel_pants (hoodie + Real Pants), mel_coat (coat + joggers), and
mel_coat_pants (coat + Real Pants). One part set, outfit KEY swaps — see
CHARACTERS.md for the recipe.

Sheet layout (walker): rows down/left/right/up, col 0 idle, cols 1-6 walk.
Frame 32x64, figure ~48 px, feet ground row y=60, anchor (15, 61).
Left row is the mirrored right row (compiler flips; glasses/hair part
asymmetries are lost in the flip and nobody at Cumulonimbus will notice).
"""

from spritelib import compose, mirror, parse_grid

# --------------------------------------------------------------------------
# Palette keys. Leg + arm grids use LOGICAL characters mapped per outfit,
# so one hand-drawn silhouette serves joggers and Real Pants alike.
# --------------------------------------------------------------------------

HEAD_KEY = {
    "o": "outline",
    "H": "hair_brown_m", "h": "hair_brown_d", "I": "hair_brown_l",
    "S": "skin_pale_m", "s": "skin_pale_d", "T": "skin_pale_l",
    "G": "outline",           # glasses
    "t": "phones_teal",       # headphones round the neck
}

HOODIE_KEY = {
    "o": "outline",
    "u": "slate_m", "U": "slate_d", "v": "slate_l",
    "W": "white",             # drawcords
    "t": "phones_teal",
    "s": "skin_pale_d",
}

COAT_KEY = {
    "o": "outline",
    "c": "coat_m", "C": "coat_d", "d": "coat_l",
    "u": "slate_m", "U": "slate_d",   # hoodie peeking at the collar
    "t": "phones_teal",
}

# Arms: logical chars -> outfit sleeves. Far arm = same grid, recolored.
ARM_HOODIE_KEY = {
    "o": "outline",
    "a": "slate_m", "A": "slate_d", "l": "slate_l",
    "x": "skin_pale_m",
}
ARM_COAT_KEY = {
    "o": "outline",
    "a": "coat_m", "A": "coat_d", "l": "coat_l",
    "x": "skin_pale_m",
}
ARM_FAR_HOODIE = {"slate_m": "slate_d", "slate_l": "slate_d",
                  "skin_pale_m": "skin_pale_d"}
ARM_FAR_COAT = {"coat_m": "coat_d", "coat_l": "coat_d",
                "skin_pale_m": "skin_pale_d"}

LEGS_JOGGER_KEY = {
    "o": "outline", "w": "shadow",
    "n": "jogger_m", "N": "jogger_d", "m": "jogger_l",
    "f": "jogger_d", "F": "outline",
    "k": "jogger_l",          # elastic cuff highlight (invisible on khaki)
    "q": "jogger_m",          # crease line (only the Real Pants show it)
    "s": "sneaker_l", "S": "sneaker_d", "z": "sneaker_d",
}
LEGS_KHAKI_KEY = {
    "o": "outline", "w": "shadow",
    "n": "khaki_m", "N": "khaki_d", "m": "khaki_l",
    "f": "khaki_d", "F": "outline",
    "k": "khaki_m",
    "q": "khaki_l",
    "s": "shoe_brown_m", "S": "shoe_brown_d", "z": "shoe_brown_d",
}

SHADOW_KEY = {"w": "shadow"}

# --------------------------------------------------------------------------
# Heads (11w x 13h). Neck skin tops the torso grid instead.
# --------------------------------------------------------------------------

HEAD_SIDE = """
...ooooo...
..oIIHHHo..
.oIIHHHHHo.
.oIHHHHHHo.
.oHHHHHHHo.
.oHHhTSSTo.
.ohHGGGGGGo
.oHhsSSSSo.
.oHhsSSSTSo
..ohsSSSso.
..oshSSSso.
...ossSso..
....osso...
"""

HEAD_FRONT = """
...ooooo...
..oIIHIHo..
.oIHHHHHHo.
.oHHHHHHHo.
.oHhHHHHho.
.ohTSTTSTo.
.oGGGSGGGo.
.osSSSSSso.
.osSTSSTso.
..osSSSso..
..osSsSso..
...osSso...
....oso....
"""

HEAD_BACK = """
...ooooo...
..oIIHHHo..
.oIIHHHHHo.
.oIHHHHHHo.
.oHHHHHHHo.
.oHHHHHHHo.
.ohHHHHHho.
.ohHHHHHho.
..ohHHHho..
..ohhHhho..
...ohhho...
....ooo....
....oso....
"""

# --------------------------------------------------------------------------
# Hoodie torsos. Side 14w x 16h (hood bunch at the back), front/back 15w.
# Top row is the neck; hem overlaps the hips by 2 px.
# --------------------------------------------------------------------------

TORSO_HOODIE_SIDE = """
..oust........
.ouuttuo......
ouuuvuuuo.....
oUuuvuuuuo....
oUuuvuuuuo....
oUuuuvuuuo....
.oUuuvuuuo....
.oUuuvuuuo....
.oUuuuuuuo....
.oUuuuuuuo....
.oUuuuuuuo....
.oUuUUuuuo....
.oUUuuUUUo....
.oUUUUUUUo....
..oUUUUUo.....
...ooooo......
"""

TORSO_HOODIE_FRONT = """
....otsto......
..oouttuoo.....
.ouuuttuuuo....
ouuuuWWuuuuo...
oUuuuWWuuuvo...
oUuuuuuuuuvo...
oUuuuuuuuuvo...
.ouuuuuuuvo....
.ouuuuuuuvo....
.ouuuuuuuvo....
.ouUUUUUUvo....
.ouUuuuuUvo....
.ouUuuuuUvo....
.ouUuuuuUvo....
..oUUUUUUo.....
...oooooo......
"""

TORSO_HOODIE_BACK = """
....ouuo.......
..oouuuuoo.....
.ouuuuuuuuo....
ouuvuuuuvuuo...
oUuvuuuuvuvo...
oUuvuuuuvuvo...
oUuuvuuvuuvo...
.ouuvuuvuvo....
.ouuuvvuuvo....
.ouuuuuuuvo....
.ouuuuuuuvo....
.ouuuuuuuvo....
.ouuuuuuuvo....
.ouuuuuuuvo....
..oUUUUUUo.....
...oooooo......
"""

# --------------------------------------------------------------------------
# Coat (worn over the hoodie; hem at the knee, legs show below).
# Side 15w x 25h, front/back 16w x 25h. Slate collar = hoodie peeking out.
# --------------------------------------------------------------------------

COAT_SIDE = """
..ouut.........
.occuuco.......
.ocdddcco......
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
.oCcccccCo.....
oCCcccccCCo....
oCCcccccCCo....
oCCCCCCCCCo....
.ooooooooo.....
"""

COAT_FRONT = """
....otuto.......
..occuutcco.....
.occccddccco....
occccdCCdccco...
oCcccdCCdccdo...
oCcccdCCdccdo...
oCccccCCcccdo...
.occccCCccco....
.occccCCccco....
.occccCCccco....
.occccCCccco....
.occccCCccco....
.occccCCccco....
.occccCCccco....
.occccCCccco....
.occccCCccco....
.oCcccCCccdo....
.oCcccCCccdo....
.oCcccCCccdo....
.oCcccCCccdo....
.oCcccCCccdo....
.oCCccCCcCdo....
.oCCCCCCCCCo....
..oCCCCCCCo.....
...ooooooo......
"""

COAT_BACK = """
....ouuo........
..occuucco......
.occccccccco....
occcdccccdcco...
oCccdccccdcdo...
oCccdccccdcdo...
oCcccddddccdo...
.occccccccco....
.occccccccco....
.occccccccco....
.occccccccco....
.occccccccco....
.occccccccco....
.occccccccco....
.occccccccco....
.occccccccco....
.oCcccccccdo....
.oCcccccccdo....
.oCcccccccdo....
.oCcccccccdo....
.oCcccccccdo....
.oCCcccccCdo....
.oCCCCCCCCCo....
..oCCCCCCCo.....
...ooooooo......
"""

# --------------------------------------------------------------------------
# Arms (7w x 14h): swing poses for the side view. Near arm drawn as-is,
# far arm = same grid recolored into shadow tones. Front/back views bake
# the arms into the torso silhouette (sleeves at the sides).
# --------------------------------------------------------------------------

ARM_SIDE_DOWN = """
oao....
oaao...
oAao...
oAao...
oAao...
oAao...
oAao...
oAao...
oAlo...
oAlo...
oalo...
.oxo...
.oxo...
..o....
"""

ARM_SIDE_FWD = """
oao....
oaao...
oAaao..
.oAao..
.oAaao.
..oAao.
..oAlo.
...oalo
...oxo.
...oxo.
....o..
.......
.......
.......
"""

ARM_SIDE_BACK = """
...oao.
..oaao.
.oaAo..
.oAao..
oAao...
oAao...
oAlo...
oalo...
oxo....
oxo....
.o.....
.......
.......
.......
"""

# --------------------------------------------------------------------------
# Legs. Side 18w x 20h (facing right, near leg = viewer side), front 16w.
# Ground contact = bottom row. Logical chars; outfit KEY picks the pants.
# --------------------------------------------------------------------------

LEGS_SIDE_IDLE = """
..onnnnno.........
..onnqnno.........
..oNnqnno.........
..oNnqnno.........
..offNnno.........
..offonno.........
..offonno.........
..offonno.........
..offonno.........
..offonno.........
..offonno.........
..offonno.........
..offonno.........
..offonno.........
..offonno.........
..okkonko.........
..offokno.........
.ozzzosso.........
.ozzzosssso.......
..oooosSSSo.......
"""

LEGS_SIDE_1 = """
....onnnno........
....onnnno........
...oNnnqnno.......
...offonqno.......
..offo.onno.......
..offo..onno......
.offo...onno......
.offo....onno.....
.offo.....onno....
offo......onno....
offo.......onno...
offo.......onno...
offo........onno..
.offo.......onno..
..offo......okno..
...offo.....okno..
....ozo....ossso..
....ozzo..ossso...
...ozzzzo.osSSSo..
....oooo..ooooo...
"""

LEGS_SIDE_2 = """
....onnnno........
....onnnno........
...oNnnqnno.......
...offonqno.......
..offo.onno.......
..offo.onnno......
..offo..onno......
.offo...onno......
.offo...onno......
.offo...onnno.....
.offo....onno.....
.offo....onno.....
.offo....onno.....
.offo....onno.....
..offo...okno.....
..offo...okno.....
...ozo..ossso.....
...ozzo.osssso....
..ozzzo.osSSSo....
...ooo...oooo.....
"""

LEGS_SIDE_3 = """
.....onnnno.......
.....onnnno.......
.....onqnno.......
.....onqnno.......
.....oNqnno.......
.....oNnnno.......
.....onnnno.......
....offonno.......
....offonno.......
....offonno.......
....offonno.......
...offo.onno......
...offo.onno......
...offzoonno......
...ofzzzoonno.....
...ozzzo.okno.....
.........okno.....
........ossso.....
........osssso....
........oSSSSo....
"""

LEGS_SIDE_4 = """
....onnnno........
....onnnno........
...onnnqnno.......
...onnoffoo.......
...onno.offo......
..onno...offo.....
..onno....offo....
..onno.....offo...
..onno......offo..
..onno......offo..
.onno........offo.
.onno........offo.
.onno........offo.
.onno.......offo..
.okno......offo...
.okno.....offo....
ossso....ozzo.....
ossso...ozzzo.....
osSSSo..ozzzzo....
.oooo....oooo.....
"""

LEGS_SIDE_5 = """
....onnnno........
....onnnno........
...onnnqnno.......
...onnoffno.......
..onno.offo.......
.onnno.offo.......
..onno..offo......
..onno..offo......
..onno..offo......
.onno...offo......
.onno...offo......
.onno...offo......
.onno...offo......
.onno...offo......
..okno..offo......
..okno..offo......
.ossso..ozzo......
osssso..ozzzo.....
oSSSSo..ozzzzo....
.oooo....oooo.....
"""

LEGS_SIDE_6 = """
.....onnnno.......
.....onnnno.......
....offnqno.......
....offnqno.......
....offnNo........
....offnnno.......
....offonno.......
....offonno.......
....offonno.......
....offonnno......
....offo.onno.....
....offo.onno.....
....offo.onnno....
....offo..onno....
....offo..okno....
....offo.ossso....
....ozzo.ossso....
...ozzzo..oSSo....
...ozzzzo.........
....oooo..........
"""

LEGS_FRONT_IDLE = """
...onnnnnno.......
...onnnnnno.......
...onnonnno.......
...oNnonnNo.......
...oNnonnNo.......
...oNnonnNo.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...oknoknno.......
...oknoknno.......
..ossoossso.......
..osssossso.......
..oSSSoSSSo.......
"""

LEGS_FRONT_1 = """
...onnnnnno.......
...onnnnnno.......
...onnonnno.......
...oNnonnNo.......
...oNnonnNo.......
...oNnonnNo.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
..onno.onnno......
..onno..onno......
..okno..okno......
..okno..okno......
.ossso..ossso.....
.ossso...ossso....
.oSSSo...oSSSo....
"""

LEGS_FRONT_2 = """
...onnnnnno.......
...onnnnnno.......
...onnonnno.......
...oNnonnNo.......
...oNnonnNo.......
...oNnonnNo.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
..onno.onno.......
..okno.okno.......
..okno.okno.......
..osso.ossso......
..osso..osso......
..oSSo..oSSo......
"""

LEGS_FRONT_3 = """
...onnnnnno.......
...onnnnnno.......
...onnonnno.......
...oNnonnNo.......
...oNnonnNo.......
...oNnonnNo.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonnno.......
...onnonno........
...oknokno........
...oknokno........
..ossoosso........
..ossoossso.......
..oSSooSSSo.......
"""

SHADOW = """
..wwwwwwwwww..
wwwwwwwwwwwwww
..wwwwwwwwww..
"""

# --------------------------------------------------------------------------
# Assembly
# --------------------------------------------------------------------------

FRAME_W, FRAME_H = 32, 64
GROUND = 60          # last opaque shoe row
LEG_H = 20
TORSO_H = 16

_heads = {k: parse_grid(g, HEAD_KEY) for k, g in
          {"side": HEAD_SIDE, "front": HEAD_FRONT, "back": HEAD_BACK}.items()}
_hoodie = {"side": parse_grid(TORSO_HOODIE_SIDE, HOODIE_KEY),
           "front": parse_grid(TORSO_HOODIE_FRONT, HOODIE_KEY),
           "back": parse_grid(TORSO_HOODIE_BACK, HOODIE_KEY)}
_shadow = parse_grid(SHADOW, SHADOW_KEY)

_arm = {}
for name, g in {"down": ARM_SIDE_DOWN, "fwd": ARM_SIDE_FWD,
                "back": ARM_SIDE_BACK}.items():
    _arm[("hoodie", name)] = parse_grid(g, ARM_HOODIE_KEY)
    _arm[("coat", name)] = parse_grid(g, ARM_COAT_KEY)

_coat = {"side": parse_grid(COAT_SIDE, COAT_KEY),
         "front": parse_grid(COAT_FRONT, COAT_KEY),
         "back": parse_grid(COAT_BACK, COAT_KEY)}

_legs = {}
for style, key in (("jogger", LEGS_JOGGER_KEY), ("khaki", LEGS_KHAKI_KEY)):
    for name, g in {"side_idle": LEGS_SIDE_IDLE, "side_1": LEGS_SIDE_1,
                    "side_2": LEGS_SIDE_2, "side_3": LEGS_SIDE_3,
                    "side_4": LEGS_SIDE_4, "side_5": LEGS_SIDE_5,
                    "side_6": LEGS_SIDE_6, "front_idle": LEGS_FRONT_IDLE,
                    "front_1": LEGS_FRONT_1, "front_2": LEGS_FRONT_2,
                    "front_3": LEGS_FRONT_3}.items():
        _legs[(style, name)] = parse_grid(g, key)

# Walk phase -> (leg grid suffix, upper bob, near-arm pose, far-arm pose).
# Arms swing opposite the near leg; recoil frames compress the upper 1 px.
SIDE_PHASES = [
    ("side_1", 0, "back", "fwd"),
    ("side_2", 1, "back", "fwd"),
    ("side_3", 0, "down", "down"),
    ("side_4", 0, "fwd", "back"),
    ("side_5", 1, "fwd", "back"),
    ("side_6", 0, "down", "down"),
]
# Front/back walks: scissor legs; 6-frame loop from 3 grids + their mirrors.
FRONT_PHASES = [("front_1", 0, False), ("front_2", 1, False),
                ("front_3", 0, False), ("front_1", 0, True),
                ("front_2", 1, True), ("front_3", 0, True)]

LEG_X, LEG_Y = 7, GROUND - LEG_H + 1     # 41
TORSO_Y = LEG_Y - TORSO_H + 2            # hem overlaps hips: 27
HEAD_Y = TORSO_Y - 12                    # chin tucks into the collar
SHADOW_POS = (8, GROUND - 2)


def _side_frame(outfit, legstyle, leg, bob, near, far):
    upper = []
    if outfit == "hoodie":
        upper = [
            (_arm[("hoodie", far)], 10, TORSO_Y + bob + 1, ARM_FAR_HOODIE),
            (_hoodie["side"], 9, TORSO_Y + bob),
            (_heads["side"], 11, HEAD_Y + bob),
            (_arm[("hoodie", near)], 13, TORSO_Y + bob + 1),
        ]
    else:
        upper = [
            (_arm[("coat", far)], 10, TORSO_Y + bob + 1, ARM_FAR_COAT),
            (_coat["side"], 9, TORSO_Y + bob),
            (_heads["side"], 11, HEAD_Y + bob),
            (_arm[("coat", near)], 13, TORSO_Y + bob + 1),
        ]
    return compose(FRAME_W, FRAME_H, [
        (_shadow, *SHADOW_POS),
        (_legs[(legstyle, leg)], LEG_X, LEG_Y),
        *upper,
    ])


def _flat_frame(outfit, legstyle, leg, bob, facing, flip):
    torso = _hoodie[facing] if outfit == "hoodie" else _coat[facing]
    tx = 8 if outfit == "hoodie" else 8
    legs = _legs[(legstyle, leg)]
    frame = compose(FRAME_W, FRAME_H, [
        (_shadow, *SHADOW_POS),
        (legs, 8, LEG_Y),
        (torso, tx, TORSO_Y + bob),
        (_heads[facing], 10, HEAD_Y + bob),
    ])
    return mirror(frame) if flip else frame


def _row_side(outfit, legstyle):
    row = [_side_frame(outfit, legstyle, "side_idle", 0, "down", "down")]
    for leg, bob, near, far in SIDE_PHASES:
        row.append(_side_frame(outfit, legstyle, leg, bob, near, far))
    return row


def _row_flat(outfit, legstyle, facing):
    row = [_flat_frame(outfit, legstyle, "front_idle", 0, facing, False)]
    for leg, bob, flip in FRONT_PHASES:
        row.append(_flat_frame(outfit, legstyle, leg, bob, facing, flip))
    return row


def _sheet_rows(outfit, legstyle):
    right = _row_side(outfit, legstyle)
    left = [mirror(f) for f in right]
    return [
        _row_flat(outfit, legstyle, "front"),   # down
        left,                                   # left
        right,                                  # right
        _row_flat(outfit, legstyle, "back"),    # up
    ]


def build():
    return {
        "mel_base": _sheet_rows("hoodie", "jogger"),
        "mel_pants": _sheet_rows("hoodie", "khaki"),
        "mel_coat": _sheet_rows("coat", "jogger"),
        "mel_coat_pants": _sheet_rows("coat", "khaki"),
    }
