"""Merle — the Bottomless Cup, end of the counter. Hand-pixeled, single
view (profile toward the room), idle + 2 talk frames.

Visual reference (his LOOK line): seed cap, flannel, coffee saucered to
cool, counter stool. Drawn SEATED with no stool of his own — he sits on
the painted stool in the diner background (anchor at his boot soles,
placed so his seat meets the painted seat). Talk frames raise the
saucer; the head never hurries.

Frame 30x54, anchor (14, 53).
"""

from spritelib import compose, parse_grid

KEY = {
    "o": "outline",
    "G": "cap_green_m", "e": "cap_green_d", "g": "cap_gold",
    "T": "skin_tan_m", "u": "skin_tan_d",
    "H": "hair_gray_m", "h": "hair_gray_d",
    "F": "flannel_m", "f": "flannel_d", "c": "flannel_check",
    "E": "denim_m", "n": "denim_d",
    "S": "saucer", "C": "coffee",
    "R": "shoe_brown_m", "r": "shoe_brown_d",
}

# Seated figure, facing left. Cap + head + plaid torso + denim legs.
# The saucer arms overlay from the left at chest height.
BODY = """
.......ooooooooo..............
.....ooGGGGGGGGGoo............
....ogggGGGGGGGGGGo...........
....ogggGGGGGGGGGGGo..........
...ooggGGGGGGGGGGGGo..........
..oooooooeGGGGGGGGGo..........
..........oeeGGGGeeo..........
.....oTTTTToooooooo...........
.....oTTTTTTTTTTTTo...........
....oTToTTTTTTToTTo...........
....oTTTTTTTTTTTTTo...........
....oTTTTTTTTTTTTo............
....ohThTTTTTTTTho............
.....ohhhTTTTThho.............
......oohhhhhhhoo.............
......oFFoooooFFFo............
.....oFFcFFFFcFFFFo...........
.....oFcccFFcccFFcFo..........
....oFFcFFFFcFFFFcFFo.........
....oFcccFFcccFFcccFo.........
....oFFcFFFFcFFFFcFFo.........
...oFFFcFFFFcFFFFcFFo.........
...oFcccFFcccFFcccFFo.........
...oFFcFFFFcFFFFcFFFo.........
...oFFcFFFFcFFFFcFFFo.........
..oFFFcFFFFcFFFFcFFFo.........
..oFFcccFFcccFFcccFFo.........
..oFFFcFFFFcFFFFcFFo..........
..offFcFFFFcFFFFcffo..........
..offFFFFFFFFFFFFfo...........
..oofffFFFFFFFfffoo...........
...oEEooffffffooEEEo..........
..oEEEEEooooooEEEEEEo.........
..oEEEEEEEEEEEEEEEEEo.........
.oEEEEEEEEEEEEEEEEEEo.........
.oEnEEEEEEEEEEEEEnEEo.........
.oEnnEEEEEEEEEEEnnEo..........
.oEnEEEEEEEoooooooo...........
.ooEEEEEoooo..................
..oEEEEEo.....................
..oEnnEEo.....................
..oEnEEno.....................
..oEnEEno.....................
..oEnEEno.....................
..oEnEEno.....................
..oEnEEno.....................
..oEnEEno.....................
..oEnEEno.....................
..onnEnno.....................
..onnEnno.....................
.oRRRnnno.....................
oRRRRRRRo.....................
oRrrRRRRo.....................
.ooooooo......................
"""

# Saucer in both hands: idle at the chest, raised to blow on it.
SAUCER = """
...........oTTo.
..oooooooooTTTo.
.oSSSSSSSSSoTTo.
..oSCCCCCSSoTo..
...oooooooooo...
"""

FRAME_W, FRAME_H = 30, 54

_body = parse_grid(BODY, KEY)
_saucer = parse_grid(SAUCER, KEY)


def _frame(saucer_dy):
    return compose(FRAME_W, FRAME_H, [
        (_body, 0, 0),
        (_saucer, 1, 24 + saucer_dy),
    ])


def build():
    return {
        "merle": [[
            _frame(0),
            _frame(-3),
            _frame(-1),
        ]]
    }
